# Generated by Django 4.2.20 on 2025-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miken_view_craft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
