# Generated by Django 4.2.20 on 2025-03-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miken_view_craft', '0002_alter_seccion_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='secciones',
        ),
        migrations.AddField(
            model_name='seccion',
            name='secciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promocion_seccion', to='miken_view_craft.pagina'),
        ),
    ]
